# Use devopsedu/webapp as the base image
FROM devopsedu/webapp

# Set the working directory within the container
WORKDIR /var/www/html

RUN apt-get update && \ apt-get install -y nginx


# Copy the PHP website files from your host to the container
COPY . .

# Expose port 80 for web traffic
EXPOSE 80

# Define the command to start the web server
CMD ["nginx", "-g", "daemon off"]
